### ISSUE TITLE
Potentially useful additions

### ISSUE THREAD

**Issue by rand5** [UniversityofWarwick/Brownian.jl#3]
Hi,
After looking a bit at this code- two comments:

**1.** It appears that the simulation algorithms are based on Weyl fBm, i.e. the Weyl fractional integral [see _Kolmogorov, A. N. The Wiener helix and other interesting curves in the Hilbert space. Dokl.
Acad. Sci. USSR 26 (1940)._] It may be useful, and in the case of physical models, more relevant to use Riemann-Liouville fBm [see _Barnes, J. A. & Allan, D. W. A Statistical Model of Flicker Noise. Proceedings of the IEEE 54, 176–178 (1966)._]. I am aware of three different algorithms for simulating R-L fBm that shouldn't be too hard to implement. There is also a relatively straight forward algorithm for simulating Weyl fBm using the Gaussian hypergeometric function, but I have not found this algorithm to be very useful.

**2.** One drawback of this implementation of the cholesky simulation approach is that it requires the length of the path to be specified _a priori_. This precludes use of the code in simulations where we would like to advance an fBm path until a stopping condition has been met (e.g. exit from time problems).

If there is any interest in these items, I'd be happy to collaborate or indicate relevant references

**Comment by scidom** [comment]
Hi @rand5, of course, you are very welcome to get involved and to contribute. Would you like to implement the alternatives you mentioned, or any other improvements for that matter, and submit a PR?

**Comment by rand5** [comment]
@scidom Sure, how about if I create a thread for each of the new algorithms, and comments/edits can be filed appropriately. I am new to Julia, so my PRs may stand to benefit greatly from optimization by someone with more experience, but they should be sufficient to sketch out a basic implementation of each algorithm

**Comment by scidom** [comment]
Sounds good, @rand5. Feel free to create a PR per algorithm and I can have a look at it before merging. If you could add in-line comments, it would be helpful.

**Comment by scidom** [comment]
@rand5, thanks for your contribution. I have opened a new PR on METADATA for a new release (v0.2.0). I will now close this issue
